// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALPKvakq4Li654UdGnn1bCf1IRa68TYao',
    appId: '1:394858722821:web:2fe4ee24be0a8e43198e6c',
    messagingSenderId: '394858722821',
    projectId: 'book-my-tables',
    authDomain: 'book-my-tables.firebaseapp.com',
    storageBucket: 'book-my-tables.appspot.com', // ✅ fix
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnmtXiln1ljS_8knOWXt3hTksdWFPfimc',
    appId: '1:394858722821:android:99e8dc90cb744102198e6c',
    messagingSenderId: '394858722821',
    projectId: 'book-my-tables',
    storageBucket: 'book-my-tables.appspot.com', // ✅ fix
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAaCDMaXfsuIxlo6uY6dtlwZkfQTHEFMc',
    appId: '1:394858722821:ios:8167d60416418953198e6c',
    messagingSenderId: '394858722821',
    projectId: 'book-my-tables',
    storageBucket: 'book-my-tables.appspot.com', // ✅ fix
    androidClientId: '394858722821-h34597lkbhb3d1864ur71fhdpo91hmmd.apps.googleusercontent.com',
    iosClientId: '394858722821-kskd33cd12j0727hn3bsdnaodfbqnu5q.apps.googleusercontent.com',
    iosBundleId: 'com.bookmytables.bookmytables',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAaCDMaXfsuIxlo6uY6dtlwZkfQTHEFMc',
    appId: '1:394858722821:ios:8167d60416418953198e6c',
    messagingSenderId: '394858722821',
    projectId: 'book-my-tables',
    storageBucket: 'book-my-tables.appspot.com', // ✅ fix
    androidClientId: '394858722821-h34597lkbhb3d1864ur71fhdpo91hmmd.apps.googleusercontent.com',
    iosClientId: '394858722821-kskd33cd12j0727hn3bsdnaodfbqnu5q.apps.googleusercontent.com',
    iosBundleId: 'com.bookmytables.bookmytables',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALPKvakq4Li654UdGnn1bCf1IRa68TYao',
    appId: '1:394858722821:web:74f5d8d456340420198e6c',
    messagingSenderId: '394858722821',
    projectId: 'book-my-tables',
    authDomain: 'book-my-tables.firebaseapp.com',
    storageBucket: 'book-my-tables.appspot.com', // ✅ fix
  );

}